name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - docs-deploy
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs-deploy
        uses: actions/checkout@v4
        with:
          ref: docs-deploy

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yaml