name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - docs-deploy
    paths:
      - 'mkdocs.yaml'
      - 'docs/**'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs-deploy
        uses: actions/checkout@v4
        with:
          ref: docs-deploy

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install mkdocs
        run: pip install mkdocs

      - name: Deploy docs
        run: python3 -m mkdocs gh-deploy --branch gh-pages-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}